[package]
name = "rbx-tree"
version = "0.1.0"
authors = ["lgreathouse <me@lpghatguy.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.7", features = ["v4", "serde"] }

[dev-dependencies]
serde_json = "1.0"
