[package]
name = "rbx_binary"
version = "0.1.0"
authors = ["lgreathouse <me@lpghatguy.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"
log = "0.4.6"
lz4 = "1.23.1"
rbx_tree = { path = "../rbx_tree" }

[dev-dependencies]
env_logger = "0.6.0"
